elasticsearch:
  host: '469c3fcba4d983641ddd30557d30b356.us-east-1.aws.found.io'
  port: 9243
  protocol: 'https'
  log: 'debug'
  username: 'hive'
  password: '1nktv1sjeS'
  index: 'bigboards-hive-dev'
auth0:
  secret: 'eDhasv9bVEdGKnnR2VYptKwjc7mMcBoM4bdqahxOtaeXEenbhFQ4je5z2zhjfciB'
ga: ''
architectures:
  - all
  - armv7l
  - x86_64